### PR TITLE
updated test to show merge overrides values with last defined.  updat…

### PR DESCRIPTION
**Pull request by lucastheisen**
…ed help to specify that last defined value wins

### CODE REVIEW

**Comment by lucastheisen** [comment]
@yoshiya8, does this satisfy your concerns as to documentation?  The [README.md](https://github.com/pastdev/clconf/blame/9c8beecb8737e333c11392b993aa068f202f0823/README.md#L5) says:

> See `clconf --help` for details.

And the help now says:

> ... Last defined value takes precedence when merged.

**Comment by yoshiya8** [comment]
May want to update readme.md with precedence rules.

**Comment by lucastheisen** [comment]
@yoshiya8 , how about [this](https://github.com/pastdev/clconf/blob/31daaad4d7c3c51dbca1682acbc4fbcd364299e3/README.md#configuration)

**Comment by yoshiya8** [comment]
That is perfect

**Pull request merged**
